---
# tasks file for ansible-role-ntp
- name: "Install ntpd"
  apt: name=ntp
- name: "Update ntp.conf"
  template:
    src: "ntp.conf.j2"
    dest: "/etc/ntp.conf"
    owner: "root"
    group: "root"
    mode: 0644
  notify: "Restart ntp service"
- name: "Allow to NTP server"
  ufw: rule=allow direction=in to_port=123 proto=udp
- name: "Stop systemd-timesyncd service"
  service:
    name: systemd-timesyncd.service
    enabled: no
    state: stopped
